// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhPBE_ECPjWh6Aa0qhARCztKH_fbof5vI',
    appId: '1:832592716654:web:20a5212b50d8da4a65577f',
    messagingSenderId: '832592716654',
    projectId: 'video-helper-21817',
    authDomain: 'video-helper-21817.firebaseapp.com',
    storageBucket: 'video-helper-21817.firebasestorage.app',
    measurementId: 'G-FKVWJYVSHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABvP-n48rybcruAUCQaJzgmH1PzQN6CYM',
    appId: '1:832592716654:android:3bfacc3d4296109065577f',
    messagingSenderId: '832592716654',
    projectId: 'video-helper-21817',
    storageBucket: 'video-helper-21817.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgGADtuDHt_qRfjVNfApgrUe9E28dwwrI',
    appId: '1:832592716654:ios:ac715fa0b6bd8a6365577f',
    messagingSenderId: '832592716654',
    projectId: 'video-helper-21817',
    storageBucket: 'video-helper-21817.firebasestorage.app',
    androidClientId: '832592716654-2peb9sads1v01fe7m09kq2cj01k9ivdj.apps.googleusercontent.com',
    iosClientId: '832592716654-v0t0inj7aaoo8vsin7l1k071j9hsuquk.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgGADtuDHt_qRfjVNfApgrUe9E28dwwrI',
    appId: '1:832592716654:ios:ac715fa0b6bd8a6365577f',
    messagingSenderId: '832592716654',
    projectId: 'video-helper-21817',
    storageBucket: 'video-helper-21817.firebasestorage.app',
    androidClientId: '832592716654-2peb9sads1v01fe7m09kq2cj01k9ivdj.apps.googleusercontent.com',
    iosClientId: '832592716654-v0t0inj7aaoo8vsin7l1k071j9hsuquk.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhPBE_ECPjWh6Aa0qhARCztKH_fbof5vI',
    appId: '1:832592716654:web:ef4d41d6988f5f1b65577f',
    messagingSenderId: '832592716654',
    projectId: 'video-helper-21817',
    authDomain: 'video-helper-21817.firebaseapp.com',
    storageBucket: 'video-helper-21817.firebasestorage.app',
    measurementId: 'G-7H2BGGXF38',
  );
}
